name: release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


env: 
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ fromJSON(env)}} "